### ISSUE TITLE
UI nitpick

### ISSUE THREAD

**Issue by FGMatej** [zakmasood/HexRedone#5]
"No buildings can be placed on tile" works only on earth

When you click on the cyan tile or elsewhere (none) vs the brown tile

It to say "No buildings can be placed on tile"

Windows 11, that is all

N/A

**Comment by zakmasood** [comment]
Cyan tile is natural gas, currently missing from the taxonomy, will fix, however no buildings not being able to be built on earth is intended behaviour.
