### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by FGMatej** [zakmasood/HexRedone#7]
Counters stopping at odd numbers, Tree - 700, Water - 200, Coal - 1100, Iron - 2088, Copper - 4188, Uranium - 1678 , Stone - 1700, Gold - 2376

Let it run for a while 

It should run for an infinite amount of time

Windows 11

N/A

**Comment by zakmasood** [comment]
Factories not running for an infinite amount of time is the intended behavior, the factory collects 100 resources and then stops, waiting for user input to either click on it or delete it with SHIFT+LMB.

The odd material counts however needs to be rectified, have you noticed them stopping at non 100 increments?
